name:
  Hello World!
  # more help on: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

on:
  push:
    branches:
      - master
      # this is comment, my origin & branch is set to master on both ends

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello World!"
      - name: Date is
        run: date
      - name: Directory content
        run: ls -l
        # why are these steps tagged as - name instead of - id ? something to think about
