name: Deployment pipeline

on:
  push:
    branches:
      - master
      - newfeaturebytuomo
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '21.0.0'
      - name: Install dependencies
        run: npm install
      # Enviroment setup above and the very important test stuff after this comment line
      - name: Check style
        run: npm run eslint
      # '- name' is optional. You can use '- run: npm run eslint' and the command will be the name as default
      - name: Build
        run: npm run build
      - name: Tests with jest
        run: npm run test
      # end to end testing with cypress
      - name: End to end testing with cypress
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
        # deployment to Render
      - name: Render Depoloyment trigger after successful tests
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: curl https://api.render.com/deploy/srv-${{secrets.RENDER_SERVICEID}}?key=${{secrets.RENDER_APIKEY}}
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu@latest
    steps:
      - name: Bumb up the version number
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          DEFAULT_BUMP: patch
          WITH_V: true
          INITIAL_VERSION: 1.0.0
